/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DDomainRouteImport } from './routes/d.$domain'
import { Route as AuthenticatedPortfolioRouteImport } from './routes/_authenticated/portfolio'
import { Route as AuthenticatedLandersRouteImport } from './routes/_authenticated/landers'
import { Route as AuthenticatedGadgetAiRouteImport } from './routes/_authenticated/gadget-ai'
import { Route as AuthenticatedDealRoomRouteImport } from './routes/_authenticated/deal-room'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAccountRouteImport } from './routes/_authenticated/account'
import { Route as ApiPublicWebhooksEscrowRouteImport } from './routes/api/public/webhooks/escrow'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DDomainRoute = DDomainRouteImport.update({
  id: '/d/$domain',
  path: '/d/$domain',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPortfolioRoute = AuthenticatedPortfolioRouteImport.update({
  id: '/portfolio',
  path: '/portfolio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLandersRoute = AuthenticatedLandersRouteImport.update({
  id: '/landers',
  path: '/landers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedGadgetAiRoute = AuthenticatedGadgetAiRouteImport.update({
  id: '/gadget-ai',
  path: '/gadget-ai',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDealRoomRoute = AuthenticatedDealRoomRouteImport.update({
  id: '/deal-room',
  path: '/deal-room',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAccountRoute = AuthenticatedAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiPublicWebhooksEscrowRoute = ApiPublicWebhooksEscrowRouteImport.update({
  id: '/api/public/webhooks/escrow',
  path: '/api/public/webhooks/escrow',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deal-room': typeof AuthenticatedDealRoomRoute
  '/gadget-ai': typeof AuthenticatedGadgetAiRoute
  '/landers': typeof AuthenticatedLandersRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/d/$domain': typeof DDomainRoute
  '/api/public/webhooks/escrow': typeof ApiPublicWebhooksEscrowRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/account': typeof AuthenticatedAccountRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/deal-room': typeof AuthenticatedDealRoomRoute
  '/gadget-ai': typeof AuthenticatedGadgetAiRoute
  '/landers': typeof AuthenticatedLandersRoute
  '/portfolio': typeof AuthenticatedPortfolioRoute
  '/d/$domain': typeof DDomainRoute
  '/api/public/webhooks/escrow': typeof ApiPublicWebhooksEscrowRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/account': typeof AuthenticatedAccountRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/deal-room': typeof AuthenticatedDealRoomRoute
  '/_authenticated/gadget-ai': typeof AuthenticatedGadgetAiRoute
  '/_authenticated/landers': typeof AuthenticatedLandersRoute
  '/_authenticated/portfolio': typeof AuthenticatedPortfolioRoute
  '/d/$domain': typeof DDomainRoute
  '/api/public/webhooks/escrow': typeof ApiPublicWebhooksEscrowRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/account'
    | '/dashboard'
    | '/deal-room'
    | '/gadget-ai'
    | '/landers'
    | '/portfolio'
    | '/d/$domain'
    | '/api/public/webhooks/escrow'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/account'
    | '/dashboard'
    | '/deal-room'
    | '/gadget-ai'
    | '/landers'
    | '/portfolio'
    | '/d/$domain'
    | '/api/public/webhooks/escrow'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/account'
    | '/_authenticated/dashboard'
    | '/_authenticated/deal-room'
    | '/_authenticated/gadget-ai'
    | '/_authenticated/landers'
    | '/_authenticated/portfolio'
    | '/d/$domain'
    | '/api/public/webhooks/escrow'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  DDomainRoute: typeof DDomainRoute
  ApiPublicWebhooksEscrowRoute: typeof ApiPublicWebhooksEscrowRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/d/$domain': {
      id: '/d/$domain'
      path: '/d/$domain'
      fullPath: '/d/$domain'
      preLoaderRoute: typeof DDomainRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/portfolio': {
      id: '/_authenticated/portfolio'
      path: '/portfolio'
      fullPath: '/portfolio'
      preLoaderRoute: typeof AuthenticatedPortfolioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/landers': {
      id: '/_authenticated/landers'
      path: '/landers'
      fullPath: '/landers'
      preLoaderRoute: typeof AuthenticatedLandersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/gadget-ai': {
      id: '/_authenticated/gadget-ai'
      path: '/gadget-ai'
      fullPath: '/gadget-ai'
      preLoaderRoute: typeof AuthenticatedGadgetAiRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/deal-room': {
      id: '/_authenticated/deal-room'
      path: '/deal-room'
      fullPath: '/deal-room'
      preLoaderRoute: typeof AuthenticatedDealRoomRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/account': {
      id: '/_authenticated/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthenticatedAccountRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/public/webhooks/escrow': {
      id: '/api/public/webhooks/escrow'
      path: '/api/public/webhooks/escrow'
      fullPath: '/api/public/webhooks/escrow'
      preLoaderRoute: typeof ApiPublicWebhooksEscrowRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccountRoute: typeof AuthenticatedAccountRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedDealRoomRoute: typeof AuthenticatedDealRoomRoute
  AuthenticatedGadgetAiRoute: typeof AuthenticatedGadgetAiRoute
  AuthenticatedLandersRoute: typeof AuthenticatedLandersRoute
  AuthenticatedPortfolioRoute: typeof AuthenticatedPortfolioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccountRoute: AuthenticatedAccountRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedDealRoomRoute: AuthenticatedDealRoomRoute,
  AuthenticatedGadgetAiRoute: AuthenticatedGadgetAiRoute,
  AuthenticatedLandersRoute: AuthenticatedLandersRoute,
  AuthenticatedPortfolioRoute: AuthenticatedPortfolioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  DDomainRoute: DDomainRoute,
  ApiPublicWebhooksEscrowRoute: ApiPublicWebhooksEscrowRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
